# H4I CI/CD Pipeline - Firebase + Node.js Projects
# 
# This workflow is specifically designed for:
# - Frontend: React/Next.js with TypeScript
# - Backend: Firebase Cloud Functions (Node.js + optional Python)
# - Deployment: Firebase Hosting
# - Package Manager: npm
#
# For other tech stacks, see additional workflow files in this directory
# or contribute new workflows as the organization grows

name: Firebase Node.js CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  # Frontend CI Job
  frontend-ci:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: |
        if npm run | grep -q "lint"; then
          npm run lint
        else
          echo "No lint script found, skipping..."
        fi
      
    - name: Run type check
      run: |
        if npm run | grep -q "type-check"; then
          npm run type-check
        else
          echo "No type-check script found, skipping..."
        fi
      continue-on-error: true
      
    - name: Run tests
      run: |
        if npm run | grep -q "test"; then
          npm run test
        else
          echo "No test script found, skipping..."
        fi
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          build/
          .next/
        retention-days: 7

  # Backend CI Job (Firebase Functions)
  backend-ci:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false && (contains(github.event.head_commit.message, 'functions') || contains(github.event.head_commit.message, 'backend'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check if functions directory exists
      id: check-functions
      run: |
        if [ -d "functions" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "No functions directory found, skipping backend CI"
        fi
      
    - name: Setup Node.js
      if: steps.check-functions.outputs.exists == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'functions/package-lock.json'
        
    - name: Install Firebase CLI
      if: steps.check-functions.outputs.exists == 'true'
      run: npm install -g firebase-tools
      
    - name: Install functions dependencies
      if: steps.check-functions.outputs.exists == 'true'
      run: |
        cd functions
        npm ci
        
    - name: Run functions linter
      if: steps.check-functions.outputs.exists == 'true'
      run: |
        cd functions
        if npm run | grep -q "lint"; then
          npm run lint
        else
          echo "No lint script found in functions, skipping..."
        fi
        
    - name: Build functions
      if: steps.check-functions.outputs.exists == 'true'
      run: |
        cd functions
        if npm run | grep -q "build"; then
          npm run build
        else
          echo "No build script found in functions, skipping..."
        fi

  # Python Backend CI Job (if applicable)
  python-backend-ci:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false && contains(github.event.head_commit.message, 'python')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f functions-python/requirements.txt ]; then
          pip install -r functions-python/requirements.txt
        fi
        
    - name: Run Python linter
      run: |
        if [ -f requirements.txt ] || [ -f functions-python/requirements.txt ]; then
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        fi

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run npm audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true

  # Deploy Job (only on main branch)
  deploy:
    needs: [frontend-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[skip deploy]') == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase
      run: |
        if [ -f "firebase.json" ]; then
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }}
        else
          echo "No firebase.json found, skipping Firebase deployment"
        fi
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }} 